<?php

/**
 * @file
 * Contains ckeditor_layouts.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckeditor_layouts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ckeditor_layouts module.
    case 'help.page.ckeditor_layouts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CKEditor Content Templates plugin for Drupal 8') . '</p>';
      return $output;

    default:
  }
}
